#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
	/tmp/leftwm-theme-down
	rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Set keyboard to AZERTY BE
#setxkbmap be

# keybindings daemon
sxhkd -c ~/.config/leftwm/sxhkd/sxhkdrc &

function run {
	if ! pgrep -x $(basename $1 | head -c 15) 1>/dev/null;
	then
		$@&
	fi
}

# Some applications to start
# nm-applet &
# xfce4-power-manager &
numlockx on &
# run xfce4-clipman


# Launch picom if installed
if [ -x "$(command -v picom)" ]; then
	picom --experimental-backends &
fi

# Set the theme.ron config
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"

# Set wallpaper using feh
if [ -x "$(command -v feh)" ]; then
	feh --bg-scale "$SCRIPTPATH"/background.jpg &
fi

# Launch dunst if installed
if [ -x "$(command -v dunst)" ]; then
	dunst &
fi

# Polybar
index=0
monitors="$(polybar -m | sed s/:.*//)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  let indextemp=index+1
  monitor=$(sed "$indextemp!d" <<<"$monitors")
  barname="example$index"
  monitor=$monitor offset=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  let index=indextemp
done
